### ISSUE TITLE
Information regarding VMProtect

### ISSUE THREAD

**Issue by gihov** [EugeneSunrise/SkinChanger#1]
Hi, I would like to know which version of VMProtect you use, I tried free version and the file is 1Mo not 5.8Mo.

**Comment by EugeneSunrise** [comment]
Yo, VMProtect Ultimate(crack), version 3.4.0
Options:
Options-->Detection--> Debugger = User-mode + Kernel-mode
Options-->Detection--> Virtualization Tools = Yes

**Comment by gihov** [comment]
You used ultimate version that's probably why ! I want to automate the build of the binary trough a CI/CD pipeline, so I will try using open source packer :)
